server:
  port: 8080

spring:
    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
                trace: false
                web-allow-others: false
    datasource:
        password: password
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:~/testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS DBPEF;
        username: ${DATABASE_USER:sa}
        initialization-mode: always
        initialize: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        open-in-view: false
        generate-ddl: false
        properties:
            hibernate:
                format_sql: true
                validator:
                    apply_to_ddl: false